// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7QkoZLIpXceA-lACxfeLtN58evrzt7DE',
    appId: '1:241778347714:web:ce9538ebdd6f3ad345b55b',
    messagingSenderId: '241778347714',
    projectId: 'nomad-10weeks-final-proje',
    authDomain: 'nomad-10weeks-final-proje.firebaseapp.com',
    storageBucket: 'nomad-10weeks-final-proje.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyZRhFDhP9Sddop50_Icrz5yOU4zvgjFo',
    appId: '1:241778347714:android:c024d5d6d95a651545b55b',
    messagingSenderId: '241778347714',
    projectId: 'nomad-10weeks-final-proje',
    storageBucket: 'nomad-10weeks-final-proje.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6oUl-p4n8Wx_Ni6R8BAnptK0crmIZh1Y',
    appId: '1:241778347714:ios:e6772b7f34d801cf45b55b',
    messagingSenderId: '241778347714',
    projectId: 'nomad-10weeks-final-proje',
    storageBucket: 'nomad-10weeks-final-proje.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6oUl-p4n8Wx_Ni6R8BAnptK0crmIZh1Y',
    appId: '1:241778347714:ios:6a8c00e558bd7e4845b55b',
    messagingSenderId: '241778347714',
    projectId: 'nomad-10weeks-final-proje',
    storageBucket: 'nomad-10weeks-final-proje.appspot.com',
    iosBundleId: 'com.example.finalProject.RunnerTests',
  );
}
